[cursor]
style = { blinking = "Always", shape = "Underline" }


[font]
size = 11
normal = { family = "JetBrainsMonoNLNF" }

[window]
opacity = 0.8
dimensions = { columns = 118, lines = 32 }
padding  = { x = 4, y = 4 }
position = { x = 326, y = 162 }
title = ""
dynamic_title = true

[scrolling]
history = 2000

[keyboard]
bindings = [
{ key = "Enter", mods = "Control", action = "CreateNewWindow" },
{ key= "V", mods = "Control", action = "Paste"},
{ key = "W", mods = "Control|Shift", action = "Quit" },
{ key = "H", mods = "Control", action = "Minimize" },
{ key = "M", mods = "Control", action = "ToggleFullscreen" }
]


[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]
